### ISSUE TITLE
Loading the dataset from sklearn provides a dataset which is different than that described

### ISSUE THREAD

**Issue by makeithappen-lab** [learn-co-curriculum/dsc-dealing-with-categorical-variables-lab#1]
Just ran the Dealing wiht Categoricals lab notebook as is -- importing the data from SKlearn.
However, when inspecting the boston data -- one key is missing - 'filename'  and after importing to Pandas,  the target value MEDV  (median home value) is not in the dataset.  

In the Categoricals lab markdown it says "Let's convert the target to a dataframe as well, and assign the column name 'MEDV' ".  

What's unclear is that the word "target"  refers to one of the keys in the boston data,  because the sentence reads very naturally in standard English,  it doesn't sound like we ought to be looking at a different key.

Some students went as far as to ask others for the csv which has the data rather than realizing it the data was in there,  but just in a different key.  Kind of defeats the purpose of realizing that we need to look at other keys in the data.

**Comment by mas16** [comment]
Thanks makeithappen-lab! The text has been updated to explicitly state that target is a different key.
